name: panda_admin
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  fl_chart: ^0.70.0
  intl: ^0.20.1
  provider: ^6.1.2
  firebase_messaging: ^15.1.6
  pdf: ^3.11.1
flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
  assets:
    - assets/images/

