name: panda_admin
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  fl_chart: ^0.70.0
  intl: ^0.20.1
  provider: ^6.1.2
  firebase_messaging: ^15.1.6
  pdf: ^3.11.1
  uuid: ^4.5.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  whatsapp_unilink: ^2.1.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
flutter:
  uses-material-design: true  
  assets:
    - assets/images/

